### PR TITLE
prestwich/home indexing

### PR DESCRIPTION
**Pull request by prestwich**
- adds local DB indexing of home events 

TODO: 
- [x] make play nice with prover sync
- [x] stop duplicating 3x in storage
- [x] requests stop and wait for sync to catch up
- [x] configurable chunk size 
- [x] figure out when we caught up to chain

### CODE REVIEW

**Comment by prestwich** [comment]
@emberian sorry for making a very large refactor while you have open PRs. This is to address urgent mainnet polygon stuff

**Review by emberian — DISMISSED** [review]

**Comment by prestwich** [comment]
@yourbuddyconner let's run this today and check that things aren't obviously broken 😂

**Comment by yourbuddyconner** [comment]
```
# HELP optics_span_duration_sec Duration from span creation to span destruction
# TYPE optics_span_duration_sec histogram
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="0.005"} 5
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="0.01"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="0.025"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="0.05"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="0.1"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="0.25"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="0.5"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="1"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="2.5"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="5"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="10"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_base::home",le="+Inf"} 6
optics_span_duration_sec_sum{VERSION="0.1.0",span_name="produce_update",target="optics_base::home"} 0.02409075
optics_span_duration_sec_count{VERSION="0.1.0",span_name="produce_update",target="optics_base::home"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="0.005"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="0.01"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="0.025"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="0.05"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="0.1"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="0.25"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="0.5"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="1"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="2.5"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="5"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="10"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home",le="+Inf"} 6
optics_span_duration_sec_sum{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home"} 0.023828915
optics_span_duration_sec_count{VERSION="0.1.0",span_name="produce_update",target="optics_ethereum::home"} 6
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="0.005"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="0.01"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="0.025"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="0.05"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="0.1"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="0.25"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="0.5"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="1"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="2.5"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="5"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="10"} 1
optics_span_duration_sec_bucket{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home",le="+Inf"} 1
optics_span_duration_sec_sum{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home"} 0.002599579
optics_span_duration_sec_count{VERSION="0.1.0",span_name="updater",target="optics_ethereum::home"} 1
```

- I notice on the processor target is different but the span `produce_update` is duplicated. Not sure if intentional. 
- Could we add an `agent` label to these metrics?

**Comment by yourbuddyconner** [comment]
Validated this on `dev`, no crashes

**Review by yourbuddyconner — APPROVED** [review]

**Pull request merged**
