### PR TITLE
bug: fix wrong variable assignment in pre-commit.sh

### PR DESCRIPTION
**Pull request by YoduYodu**

### CODE REVIEW

**Comment by prestwich** [comment]
I think that those variable assignments are correct, as we use `sort` later. The variables are set to match the output format of the commands

```
james@Sisyphus ~                                                     [14:10:19]
> $ git --version                                                    ⬡ 15.14.0
git version 2.31.1

james@Sisyphus ~                                                     [14:10:21]
> $ cargo version                                                    ⬡ 15.14.0
cargo 1.52.0 (69767412a 2021-04-21)
```

**Comment by YoduYodu** [comment]
> I think that those variable assignments are correct, as we use `sort` later. The variables are set to match the output format of the commands
> 
> ```
> james@Sisyphus ~                                                     [14:10:19]
> > $ git --version                                                    ⬡ 15.14.0
> git version 2.31.1
> 
> james@Sisyphus ~                                                     [14:10:21]
> > $ cargo version                                                    ⬡ 15.14.0
> cargo 1.52.0 (69767412a 2021-04-21)
> ```

Maybe I'm mistaken(I just started learning to write bash today...),
but aren't they duplicates in line 33 `if (echo min version $MIN_GIT; git --version) | sort -Vk3 | tail -1 | grep -q git`
and line 44 `if (echo min $MIN_CARGO; cargo --version) | sort -Vk2 | tail -1 | grep -q cargo`?

Besides, this change does run the checks. For example, it aborts if I change MIN_GIT to 2.50.0

**Comment by prestwich** [comment]
oh shoot you're 100% correct. They are totally duplicated there

**Review by prestwich — APPROVED** [review]
good catch

**Comment by YoduYodu** [comment]
@prestwich Can I have the auth to merge?

**Comment by prestwich** [comment]
yes. in general, you can merge as long as the PR has 1 approval from a team member

**Comment by YoduYodu** [comment]
But now it is "You’re not authorized to merge this pull request." near a gray button.

**Comment by YoduYodu** [comment]
Merging is blocked
The base branch restricts merging to authorized users.
----
Maybe I should add myself to CODEOWNER?

**Pull request merged**
