### PR TITLE
refactor: combine lib and script folders to js folder

### PR DESCRIPTION
**Pull request by ErinHales**

### CODE REVIEW

**Comment by ErinHales** [comment]
Was seeing this error when running the pre-commit script, but not when I ran the `test-all` script.  Not sure if this is related to something I did. 
Screen Shot 2021-06-08 at 11 17 32 AM

**Comment by prestwich** [comment]
this might be related to the way we're mixing providers? the tests could really use an overhaul in TS 😬

**Comment by ErinHales** [comment]
Have confirmed this is happening on main as well, so I will open an issue for it.  I can open an issue for ts tests as well

**Comment by prestwich** [comment]
to resolve conflicts, rebase onto main and run `npx hardhat typechain` from the optics-core directory

**Comment by ErinHales** [comment]
Oh, I didn't realize there were merge conflicts!  Ok, those are taken care of

**Review by prestwich — APPROVED** [review]

**Comment by prestwich** [comment]
more merge conflicts in autogenerated files 🙌

**Review by prestwich — APPROVED** [review]

**Pull request merged**
